apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-env-data
  namespace: crud
data:
  .env: |
    APP_ENV=development
    LOG_LEVEL=debug
    MONGODB_CONNECTION=mongodb+srv://root:change-me@mongodb-headless.mongodb.svc.cluster.local/?ssl=false
    STREAMS_CLIENT_ADDRESS=streams.streams.svc.cluster.local:9000
    STREAMS_CLIENT_KEEPALIVE_INTERVAL=40
    STREAMS_CLIENT_KEEPALIVE_TIMEOUT=3
    STREAMS_CLIENT_SEND_TIMEOUT=1
    STREAMS_CLIENT_GROUP_ID=crud
    PROJECTIONS_CLIENT_ADDRESS=projections.projections.svc.cluster.local:9000
    PROJECTIONS_CLIENT_KEEPALIVE_INTERVAL=40
    PROJECTIONS_CLIENT_KEEPALIVE_TIMEOUT=3
    PROJECTIONS_CLIENT_SEND_TIMEOUT=1
