apiVersion: v1
kind: Service
metadata:
  name: crud
  namespace: crud
spec:
  type: ClusterIP
  selector:
    app: crud
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000
